spring.application.name=monitoring
###############################################
### DATABASE CONNECTIVITY CONFIGURATIONS ###
###############################################
database.ip=${DB_IP:monitoring-db}
database.port=${DB_PORT:5432}
database.user=${DB_USER:dogmedve}
database.password=${DB_PASSWORD:root}
database.name=${DB_DBNAME:sd_tema2_monitoring}
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${database.ip}:${database.port}/${database.name}
spring.datasource.username=${database.user}
spring.datasource.password=${database.password}
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.show_sql=true
server.tomcat.threads.max=1
###############################################
### LOGGING CONFIGURATIONS ###
###############################################
logging.level.root=warn
logging.level.org.springframework=warn
logging.level.ro.tuc=warn
###############################################
### EMBEDDED TOMCAT CONFIGURATIONS ###
###############################################
server.port=${PORT:8084}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
# Listener configuration
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=3