spring.application.name=device_data_simulator
server.port=${PORT:8090}
devices.service.url=http://localhost:8081
#RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin